SEED: 42
USE_AMP: False
VERBOSE: True
PATHS:
  SHARD_ROOT: /scratch/work/brazzan1/chexpert
  EXPERIMENT_NAME: "efficientnet_barlowTwin"
  OUT_DIR: ../experiments
TRAIN:
  IMG_SIZE: 256
  LR: 1e-4
  BATCH_SIZE: 128
  N_EPOCHS: 20
  WEIGHT_DECAY: 1e-4
  MODEL_NAME: efficientnet_barlowTwin
  MODEL_SAVE_PATH: ../saved_models/efficientnet_barlowTwin
  NUM_WORKERS: 4