SEED: 42
USE_AMP: False
VERBOSE: True
PATHS:
  SHARD_ROOT: /l/Work/aalto/chest-xray-ssl/input/chexpert-shards
  EXPERIMENT_NAME: "resnet50-baseline"
  OUT_DIR: ../experiments
TRAIN:
  IMG_SIZE: 128
  LR: 1e-4
  BATCH_SIZE: 32
  N_EPOCHS: 10
  WEIGHT_DECAY: 0.0
  MODEL_NAME: resnet50
  MODEL_SAVE_PATH: ../saved_models/resnet50
  NUM_WORKERS: 4