SEED: 42
USE_AMP: False
VERBOSE: True
PATHS:
  SHARD_ROOT: /scratch/work/brazzan1/chexpert
  EXPERIMENT_NAME: "resnet18-baseline"
  OUT_DIR: ../experiments
TRAIN:
  IMG_SIZE: 256
  LR: 1e-4
  BATCH_SIZE: 32
  N_EPOCHS: 20
  WEIGHT_DECAY: 0.0
  MODEL_NAME: resnet18
  MODEL_SAVE_PATH: ../saved_models/resnet18
  NUM_WORKERS: 4